services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    networks:
      - inkLink_doc
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.runCommand("ping").ok']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - inkLink_doc
    volumes:
      - redis-data:/data

networks:
  inkLink_doc:
    driver: bridge

volumes:
  mongo-data:/data/db:
  redis-data:/data:
